server:
  port: 8091
spring:
  application:
    name: orchestrator
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: false
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    database-platform: fully.qualified.classname.NoToastPostgresSQLDialect

#  autoconfigure:
#    exclude: org.axonframework.springboot.autoconfig.JpaAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.axonframework.springboot.autoconfig.JpaEventStoreAutoConfiguration, org.axonframework.springboot.autoconfig.TransactionAutoConfiguration
axon:
  distributed:
    enabled: true
    load-factor: 100
    spring-cloud:
      fallback-to-http-get: true
      fallback-url: /message-routing-information
      mode: rest
      enable-ignore-listing: true
#      enable-accept-all-commands: true
      rest-mode-url: /message-routing-information
  serializer:
    general: jackson
    events: jackson
    messages: jackson
logging:
  level:
    org:
      axonframework: debug


