server:
  port: 8010
spring:
  application:
    name: apiGateway

zuul:
  sensitiveHeaders: Cookie,Set-Cookie,FeignInvocationUser,FeignInvocationUserId

#restricting logs
logging:
  level:
    cdjd.com.dremio.telemetry.api.metrics: ERROR
    cdjd.com.dremio.sabot.rpc.user: ERROR
