server:
  port: 9060
spring:
  application:
    name: collaboration
  autoconfigure:
    exclude: org.axonframework.springboot.autoconfig.JpaAutoConfiguration, org.axonframework.springboot.autoconfig.JdbcAutoConfiguration, org.axonframework.springboot.autoconfig.JpaEventStoreAutoConfiguration