server:
  port: 8090
spring:
  application:
    name: recordstore
    
#restricting logs    
logging:
  level:
    cdjd.com.dremio.telemetry.api.metrics: ERROR
    cdjd.com.dremio.sabot.rpc.user: ERROR