server:
  port: 8090
spring:
  application:
    name: recordstore
  autoconfigure:
    exclude: org.axonframework.springboot.autoconfig.JpaAutoConfiguration, org.axonframework.springboot.autoconfig.JdbcAutoConfiguration, org.axonframework.springboot.autoconfig.JpaEventStoreAutoConfiguration
