server:
  port: 8030
spring:
  application:
    name: dataset
  jpa:
    hibernate:
      #use create if you are going to create the schema for the first time
      ddl-auto: update
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        dialect: ${DATABASE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        jdbc:
          lob:
            non_contextual_creation: true
    database: postgresql
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${random.value}
  sleuth:
    sampler:
      probability: 1.0
    web:
      skipPattern: "(^cleanup.*|.+favicon.*|.+actuator.*|.+prometheus.*)"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
        
mongodb:
  hibernate:
      ddl-auto: create
  primary:
      host: localhost
      port: 27017
      database: admin
      username: root
      password: root
    
hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 2
        sleepWindowInMilliseconds: 10000