server:
  port: 8015
spring:
  application:
    name: validation
  jpa:
    hibernate:
      #use create if you are going to create the schema for the first time
      ddl-auto: ${DDL_AUTO:validate}
      flushMode: commit
      show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: ${DATABASE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        order_updates: false
        order_inserts: true
        jdbc:
          batch_size: ${DATASET_BACH_JPA_SIZE:100}
          lob:
            non_contextual_creation: true
    database: postgresql
  datasource:
    url: ${METABASE_DATASOURCE_URL:jdbc:postgresql://localhost/metabase}
    username: ${METABASE_DATASOURCE_USER_NAME:root}
    password: ${METABASE_DATASOURCE_PASSWORD:root}
    driver-class-name: ${METABASE_DATASOURCE_DRIVER_CLASS:org.postgresql.Driver}
    hikari:
      connection-timeout: ${METABASE_DATABASE_CONNECTION_TIMEOUT:60000}
      maximum-pool-size: ${METABASE_DATABASE_CONNECTION_MAXIMUM_POOL_SIZE:5}

  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${random.value}
  sleuth:
    sampler:
      probability: 1.0
    web:
      skipPattern: "(^cleanup.*|.+favicon.*|.+actuator.*|.+prometheus.*)"

management:
  endpoints:
    web:
      exposure:
        include: "${ACTUATOR_EXPOSURE_INCLUDE:*}"
  endpoint:
    health:
      show-details: always
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 2
        sleepWindowInMilliseconds: 10000
mongodb:
  hibernate:
    ddl-auto: create
  primary:
    host: localhost
    port: 27017
    database: admin
    username: root
    password: root