server:
  port: 8015
spring:
  application:
    name: validation

#restricting logs
logging:
  level:
    cdjd.com.dremio.telemetry.api.metrics: ERROR
    cdjd.com.dremio.sabot.rpc.user: ERROR