server:
  port: 8015
spring:
  application:
    name: validation
  autoconfigure:
    exclude: org.axonframework.springboot.autoconfig.JpaAutoConfiguration, org.axonframework.springboot.autoconfig.JdbcAutoConfiguration, org.axonframework.springboot.autoconfig.JpaEventStoreAutoConfiguration