template header
ruleid
typevalidation
whencondition
condition1
condition2


package src.main.resources
import org.eea.validation.persistence.rules.model.*;
import org.eea.interfaces.vo.validation.*;
import org.eea.interfaces.vo.dataset.*;
import org.eea.validation.util.*;

template "templateValidateRules"

rule "@{ruleid}"
dialect "java"
  when
    dataValidate : @{typevalidation}(@{whencondition});	
  then
   ValidationRuleDrools.fillValidation(dataValidate, "@{condition1}","@{condition2}","@{ruleid}");
 
   
end
	
end template
