server:
  port: 9050
spring:
  application:
    name: rod

#restricting logs
logging:
  level:
    cdjd.com.dremio.telemetry.api.metrics: ERROR
    cdjd.com.dremio.sabot.rpc.user: ERROR
    org.springframework.cloud.netflix.zuul.filters.route.support: ERROR
    org.apache.kafka.clients.consumer.internals: ERROR