export const CurrentPage = {
  EU_DATASET: 'EU_DATASET',
  DATA_COLLECTION: 'DATA_COLLECTION',
  DATAFLOW_DASHBOARDS: 'DATAFLOW_DASHBOARDS',
  DATAFLOW_FEEDBACK: 'DATAFLOW_FEEDBACK',
  DATAFLOW_HELP: 'DATAFLOW_HELP',
  DATAFLOW: 'DATAFLOW',
  DATAFLOWS: 'DATAFLOWS',
  DATASET_DESIGNER: 'DATASET_DESIGNER',
  DATASET: 'DATASET',
  PUBLIC_DATAFLOW: 'PUBLIC_DATAFLOW',
  PUBLIC_DATAFLOWS: 'PUBLIC_DATAFLOWS',
  PUBLIC_INDEX: 'PUBLIC_INDEX',
  USER_SETTINGS: 'USER_SETTINGS',
  TEST_DATASETS: 'TEST_DATASETS'
};
