export const CurrentPage = {
  DATAFLOW_DASHBOARDS: 'DATAFLOW_DASHBOARDS',
  DATAFLOW_HELP: 'DATAFLOW_HELP',
  DATAFLOW: 'DATAFLOW',
  DATAFLOWS: 'DATAFLOWS',
  DATASET_DESIGNER: 'DATASET_DESIGNER',
  DATASET: 'DATASET',
  USER_SETTINGS: 'USER_SETTINGS'
};
